### ISSUE TITLE
UI compilation workflow

### ISSUE THREAD

**Issue by doismellburning** [CanonicalLtd/serial-vault#266]
Right now, we have:

* In-tree source JS files
* In-tree compiled JS at `/static/js/bundle.js`, currently manually-built and committed

Several builds of the SV vault happen on offline machines, or machines without a JS build chain. Thus there is value in being able to clone the SV repo and get already-compiled JS.

What we want is

* Automated builds of the JS on a clean system
* A buildable self-contained source repository for SV

I propose:

* We pull out the source into the `serial-vault-ui` repo (SVU)
* GitHub Actions (since we're GitHub hosted, and this should require minimal permissions and setup) on the SVU repo to
  * Build and test the source JS (as general baseline expectation of automated building/testing)
  * File a PR against the *SV* repo containing updates to the build output

That way we have

* Automated builds of the JS (the SVU repo and associated GitHub actions)
* A self-contained SV repo (because the SVU build output ends up in the SV repo)
* Automatically _proposed_ updates to SV (the auto-created PRs) with manual acceptance (PR merge)
* Relatively little surface increase
  * SV builders don't need to grow JS compilation functionality
  * Relatively little "development-side" configuration (We use GitHub so get GitHub Actions "for free", and all they need is some YAML in the repo)

How does that sound?

**Comment by glower** [comment]
As far as I understood the documentation of the github actions we can only operate in the same repository without having to set up extra security tokens.
Some things I have discovered:
-   There is no way to automatically trigger an action in `serial-vault-ui` after we did a merge in`serial-vault` only using actions. Rather SV call an API to trigger SVU action, or SVU can pull SV with `cron` trigger
- The action automation bot can only perform write actions (like PR) on the same repo, not on other repos. For this action, it needs an extra read/write token from other repo.

**Comment by glower** [comment]
I would propose to do the build in this repo and don't use `serial-vault-ui`. The setup for the github action would be like this (this will build the js/css on push to master and create a PR for this): 
```
name: Node.js CI

on:
  push:
    branches: master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Build frontend
      run: |
        pwd
        cd webapp-admin
        npm install
        npm run build
        cp -R build/static/js ../static
        cp -R build/static/css ../static
        cp -R build/index.html ../static/app.html
    - name: Create Pull Request
      id: cpr
      uses: peter-evans/create-pull-request@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: Add js/css files
```
